/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:3054f861-eab1-4a26-90d4-a6a8f5f72238",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_qAeMshpAP",
    "aws_user_pools_web_client_id": "2sn8v8bo62jiqc2gr7pjo0u698",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://quef57xtpbezblclnzdrhatjt4.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
